# Generated by Django 2.1.4 on 2018-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='retust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('class_of_student', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'boys'), ('female', 'girls')], max_length=10)),
            ],
        ),
    ]
